# Generated by Django 3.0.8 on 2021-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'vehicle', 'verbose_name_plural': 'vehicles'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plates',
            field=models.CharField(max_length=200, null=True, verbose_name='license plates'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=200, null=True, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
    ]
