# Generated by Django 3.0.8 on 2021-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20210510_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plates',
            field=models.CharField(max_length=200, null=True, verbose_name='license'),
        ),
    ]
