# Generated by Django 3.0.8 on 2021-05-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20210510_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Phương Tiện', 'verbose_name_plural': 'Phương tiện'},
        ),
    ]
