# Generated by Django 3.0.8 on 2021-05-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20210510_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
    ]
