# Generated by Django 3.0.8 on 2021-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20210510_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plates',
            field=models.CharField(max_length=200, null=True, verbose_name='license plates'),
        ),
    ]
