# Generated by Django 3.0.8 on 2021-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20210510_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True, verbose_name='fullname')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='phone')),
                ('identity', models.CharField(max_length=200, null=True, verbose_name='identity')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
