# Generated by Django 3.0.8 on 2021-05-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='order name')),
                ('price', models.FloatField(verbose_name='price')),
                ('tax', models.FloatField(verbose_name='tax')),
                ('salary', models.FloatField(verbose_name='salary')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.Driver', verbose_name='driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.Vehicle', verbose_name='vehicle')),
            ],
        ),
    ]
