# Generated by Django 3.0.8 on 2021-05-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
    ]
