# Generated by Django 3.0.8 on 2021-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20210511_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ended',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date ended'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date started'),
        ),
    ]
