# Generated by Django 3.0.8 on 2021-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_auto_20210511_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ended',
            field=models.DateTimeField(null=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_started',
            field=models.DateTimeField(null=True, verbose_name='date started'),
        ),
    ]
