# Generated by Django 3.0.8 on 2021-05-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_auto_20210511_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.ModelVehicle', verbose_name='model'),
        ),
    ]
