# Generated by Django 3.0.8 on 2021-05-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_auto_20210515_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelvehicle',
            options={'verbose_name': 'Model Vehicle', 'verbose_name_plural': 'Model Vehicle'},
        ),
        migrations.AlterField(
            model_name='modelvehicle',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.ModelVehicle', verbose_name='model'),
        ),
    ]
