# Generated by Django 3.0.8 on 2021-05-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_auto_20210515_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ended',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date started'),
        ),
    ]
